<?php

namespace backend\models;
use yii\base\Model;


class GoodsSearchForm extends Model
{
    public $keyword;
    public $minPrice;
    public $maxPrice;
    public function rules()
    {
        return [
            [['minPrice','maxPrice'],'number'],
            ['keyword','safe']
        ]; // TODO: Change the autogenerated stub
    }
}